# Generated by Django 4.0.2 on 2022-02-27 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
